# Change these first
owner: dhvitOP # Your GitHub organization or username, where this repository lives
repo: Dumb-List-Status2 # The name of this repository

sites:
  - name: Main
    url: https://dumbbotlist.tk
  - name: Documentation
    url: https://docs.dumbbotlist.tk
  - name: API
    url: https://dumbbotlist.tk/api
  - name: Bots
    url: https://dumbbotlist.tk/bots
  - name: Servers
    url: https://dumbbotlist.tk/server
  - name: Vanity
    url: https://dumbbotlist.tk/addvanity

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dumbbotlist.tk
  # baseUrl: /your-repo-name
  theme: ocean
  favicon: https://cdn.discordapp.com/icons/849623732871757854/a_26efada30b14c63cb84f6b3676d29e82.gif?size=1024
  logoUrl: https://cdn.discordapp.com/icons/849623732871757854/a_26efada30b14c63cb84f6b3676d29e82.gif?size=1024
  name: Dumb List
  introTitle: "**You can See The Status of Dumb List Here**."
  introMessage: This Status Website will show You the real Time Status of Website
  navbar:
    - title: Status
      href: /
    - title: Bots
      href: https://dumbbotlist.tk/bots
    - title: Servers
      href: https://dumbbotlist.tk/servers

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
