# Change these first
owner: dhvitOP # Your GitHub organization or username, where this repository lives
repo: Dumb-List-Status2 # The name of this repository

sites:
  - name: Main
    url: https://dumbbotlist.tk
  - name: Documentation
    url: https://docs.dumbbotlist.tk
  - name: API
    url: https://dumbbotlist.tk/api

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dumbbotlist.tk
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/icons/849623732871757854/a_26efada30b14c63cb84f6b3676d29e82.gif?size=1024
  name: Dumb List
  introTitle: "**You can See The Status of Dumb List Here**."
  introMessage: This is in Beta Stage so Please Dont Judge This Website
  navbar:
    - title: Status
      href: /
    - title: Bots
      href: https://dumbbotlist.tk/bots
        - title: Servers
      href: https://dumbbotlist.tk/servers

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
